version: "3.9"
services:
  db_nafanya:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'
    volumes:
      - db_nafanya:/var/lib/postgresql/data
  bot:
    container_name: nafanya-bot
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db_nafanya
    environment:
      DB_HOST: db_nafanya
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: postgres
      AI_TOKEN: ${AI_TOKEN}
      BOT_TOKEN: ${BOT_TOKEN}
      SENTRY_DSN: ${SENTRY_DSN}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      DEBUG_MODE: true
volumes:
  db_nafanya:
    driver: local