FROM golang:latest AS build

# Build Delve
RUN go install github.com/go-delve/delve/cmd/dlv@latest

WORKDIR /go/src/github.com/shabablinchikow/nafanya-bot
COPY . /go/src/github.com/shabablinchikow/nafanya-bot

# Setup the compilation environment
ENV CGO_CPPFLAGS="-I/usr/include"
ENV CGO_LDFLAGS="-L/usr/lib -lpthread -lrt -lstdc++ -lm -lc -lgcc"
ENV CC="/usr/bin/gcc"
ENV CFLAGS="-march=x86-64"
ENV PKG_CONFIG_PATH="/usr/local/lib/pkgconfig"
ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOARCH=amd64

RUN go get -d -v ./...
RUN go build -C cmd -o /go/bin/nafanya-bot -gcflags "all=-N -l"

FROM ubuntu:latest

RUN apt-get update
RUN apt-get install ca-certificates -y
RUN update-ca-certificates

EXPOSE 8000 40000

WORKDIR /

COPY --from=build /go/bin/nafanya-bot /nafanya-bot
COPY --from=build /go/bin/dlv /dlv
CMD ["./dlv", "--listen=:40000", "--headless=true", "--api-version=2", "--accept-multiclient", "exec", "/nafanya-bot"]