version: "3.9"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  bot:
    container_name: nafanya-bot
    build:
      context: ./
      dockerfile: Dockerfile-local
    ports:
      - "8000:8000"
      - "40000:40000"
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    command: ./dlv --listen=:40000 --headless=true --api-version=2 --accept-multiclient exec /nafanya-bot
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: postgres
      AI_TOKEN: ${AI_TOKEN}
      BOT_TOKEN: ${BOT_TOKEN}
      SENTRY_DSN: ${SENTRY_DSN}
      DEBUG_MODE: true
volumes:
  db:
    driver: local