version: "3.9"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  bot:
    container_name: nafanya-bot
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: postgres
      AI_TOKEN: ${AI_TOKEN}
      BOT_TOKEN: ${BOT_TOKEN}
      DEBUG_MODE: true
volumes:
  db:
    driver: local