apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "deliverybot.dev/secret-checksum": {{ toJson .Values.secrets | sha256sum }}
  labels:
{{ include "app.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "app.matchLabels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "app.matchLabels" . | indent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: AI_TOKEN
              value: {{ .Values.secrets.ai_token }}
            - name: BOT_TOKEN
              value: {{ .Values.secrets.bot_token }}
            - name: DB_HOST
              value: {{ .Values.secrets.db_host }}
            - name: DB_PORT
              value: "{{ .Values.secrets.db_port }}"
            - name: DB_USER
              value: {{ .Values.secrets.db_user }}
            - name: DB_PASS
              value: {{ .Values.secrets.db_pass }}
            - name: DB_NAME
              value: {{ .Values.secrets.db_name }}
            - name: DB_SSL
              value: "{{ .Values.secrets.db_sslmode }}"
            - name: SENTRY_DSN
              value: {{ .Values.secrets.sentry_dsn }}
          ports:
            - name: http
              containerPort: {{ .Values.service.internalPort }}
              protocol: TCP
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
