name: Docker build and deploy

on:
  push:
    branches: [ "master" ]

env:
  REGISTRY: registry.digitalocean.com
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Add cert
        run: echo "${{ secrets.SSL_CERT }}" >> ssl-cert.crt
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      -
        name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: registry.digitalocean.com/shaba/nafanya-bot:${{github.sha}}, registry.digitalocean.com/shaba/nafanya-bot:master

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 kluster

      - name: Helm tool installer
        uses: Azure/setup-helm@v3

      - name: Run Helm upgrade
        run: helm upgrade --atomic --install nafanya-bot charts/app -f values.yaml --set image.tag=${{github.sha}} --set secrets.ai_token=${{ secrets.AI_TOKEN }} --set secrets.bot_token=${{ secrets.BOT_TOKEN}} --set secrets.db_pass=${{ secrets.DB_PASS }} --set secrets.db_user=${{ secrets.DB_USER }} --set secrets.db_name=${{ vars.DB_NAME }} --set secrets.db_host=${{ vars.DB_HOST }} --set secrets.db_port=${{ vars.DB_PORT }} --set secrets.db_sslmode=${{ vars.DB_SSLMODE }} --set secrets.sentry_dsn=${{ secrets.SENTRY_DSN }}
